[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && flask db upgrade && python create_plans.py"

[deploy]
startCommand = "gunicorn run:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 